const MOVIES_TO_SHOW_INITIAL = 0;
const MOVIES_TO_SHOW_ON_WIDTH_MORE_THEN_940 = 12;
const MOVIES_TO_SHOW_ON_WIDTH_LESS_THEN_940 = 8;
const MOVIES_TO_SHOW_ON_WIDTH_LESS_THEN_520 = 5;
const AMOUNT_TO_ADD_ON_WIDTH_LESS_THEN_940 = 2;
const AMOUNT_TO_ADD_ON_WIDTH_MORE_THEN_940 = 3;
const DURATION_OF_FULL_LENGTH_MOVIE = 40;
const ONE_HOUR_IN_MINUTES = 60;
const LENGTH_OF_MINUTES_TO_DISPLAY = 2;

export {
  MOVIES_TO_SHOW_INITIAL,
  MOVIES_TO_SHOW_ON_WIDTH_MORE_THEN_940,
  MOVIES_TO_SHOW_ON_WIDTH_LESS_THEN_940,
  MOVIES_TO_SHOW_ON_WIDTH_LESS_THEN_520,
  AMOUNT_TO_ADD_ON_WIDTH_LESS_THEN_940,
  AMOUNT_TO_ADD_ON_WIDTH_MORE_THEN_940,
  DURATION_OF_FULL_LENGTH_MOVIE,
  ONE_HOUR_IN_MINUTES,
  LENGTH_OF_MINUTES_TO_DISPLAY,
};
